import frames from './frames.json';
import sequence from './sequence.json';

/**
 * Single place to tune the opening scene: timings, scale, sequences and greetings.
 * Frame files and the crop box are generated by scripts/build-frames.py (frames.json);
 * the greeting playback order comes from the original manifest (sequence.json).
 */

export interface GreetingWord {
  text: string;
  lang: string;
}

/** Position as a percentage of the hero stage. `anchor` says which edge of the word sits on the point. */
export interface Slot {
  x: number;
  y: number;
  anchor: 'start' | 'center' | 'end';
  /** Direction of the short drift, in px, over the life of the word. */
  drift: [number, number];
}

export const animation = {
  frames,

  fps: { walk: 8, greeting: sequence.fps },

  /** Greeting loop: 1-based drawing ids in playback order (84 exposures at 10 fps). */
  greetingSequence: sequence.frames as number[],

  arrival: {
    /** The walk clip is 12 distinct drawings; it repeats this many times. */
    cycles: 4,
    /** Walk drawing (0-based) the approach ends on, chosen to sit closest to the standing pose. */
    endOnDrawing: 0,
    startScale: 0.13,
    endScale: 1,
    /** CSS-style cubic-bezier for the growth: slow far away, steady, settles as he arrives. */
    ease: [0.55, 0, 0.4, 1] as [number, number, number, number],
    /** Vertical transform origin inside the figure: feet climb toward the "horizon" when small. */
    originY: 0.58,
    /** Progress (0 to 1) at which the name starts to write in and greetings begin. */
    nameAt: 0.5,
    greetingsAt: 0.62,
  },

  loading: {
    /** Use the large frames when the figure needs more device pixels than this. */
    largeTierAbovePx: 1150,
    maxDevicePixelRatio: 2,
    /** How many upcoming exposures stay decoded ahead of the playhead. */
    decodeAhead: { sm: 16, lg: 10 },
    /** Give up waiting for the walk cycle and show the static pose after this long. */
    startTimeoutMs: 8000,
    prefetchConcurrency: 3,
  },

  /** Pose shown when motion is reduced or the sequence cannot load (arms crossed, smiling). */
  staticDrawing: 25,

  greetings: {
    words: [
      { text: 'Hola', lang: 'es' },
      { text: 'Hello', lang: 'en' },
      { text: 'Bonjour', lang: 'fr' },
      { text: 'Ciao', lang: 'it' },
      { text: 'Hallo', lang: 'de' },
      { text: 'Olá', lang: 'pt' },
      { text: 'こんにちは', lang: 'ja' },
      { text: 'Hej', lang: 'sv' },
    ] satisfies GreetingWord[],
    maxVisible: 3,
    lifetimeMs: [1500, 2100] as [number, number],
    fadeInMs: 480,
    fadeOutMs: 620,
    gapMs: [420, 980] as [number, number],
    /** Fraction of the figure box (x, y, w, h) that words must stay clear of. */
    keepClear: [
      [0, 0, 1, 0.2],
      [0.05, 0.2, 0.92, 0.62],
      [0.28, 0.82, 0.46, 0.18],
    ] as [number, number, number, number][],
    clearancePx: 14,
    slots: {
      desktop: [
        { x: 7, y: 11, anchor: 'start', drift: [10, -8] },
        { x: 31, y: 22, anchor: 'start', drift: [-8, -10] },
        { x: 14, y: 34, anchor: 'start', drift: [12, 6] },
        { x: 84, y: 16, anchor: 'start', drift: [8, -10] },
        { x: 88, y: 38, anchor: 'start', drift: [-8, 8] },
        { x: 85, y: 62, anchor: 'start', drift: [8, -8] },
      ] as Slot[],
      compact: [
        { x: 7, y: 7, anchor: 'start', drift: [8, -6] },
        { x: 93, y: 12, anchor: 'end', drift: [-8, -6] },
        { x: 50, y: 4, anchor: 'center', drift: [0, -8] },
        { x: 6, y: 20, anchor: 'start', drift: [8, 6] },
        { x: 94, y: 28, anchor: 'end', drift: [-8, 6] },
      ] as Slot[],
    },
  },

  /** Section titles that arrive as a pencil sketch and settle into ink (src/scripts/ink.ts). */
  ink: {
    /** Progress starts when the title's top crosses this fraction of the viewport height... */
    start: 1,
    /** ...and completes after it has travelled this fraction further up. */
    span: 0.62,
    /** Progress at which hatching starts to fill the letters, and at which the outline starts to settle. */
    hatchFrom: 0.38,
    settleFrom: 0.7,
    /** Pencil wobble of the outline, as a fraction of the font size. */
    wobble: 0.022,
    noise: 0.015,
    fps: 6,
    /** Turbulence seeds for the two pencil passes, one pair per boil drawing. */
    seeds: [
      [3, 11],
      [7, 19],
      [13, 29],
    ] as [number, number][],
  },

  /** Layout switch shared by CSS (see Hero.astro) and the greeting slots. */
  compactQuery: '(max-width: 760px), (max-aspect-ratio: 4/5)',
} as const;

export type AnimationConfig = typeof animation;
